definitions:
  dto.CompareRequest:
    description: Request payload for comparing two items
    properties:
      loser_id:
        type: string
      winner_id:
        type: string
    type: object
info:
  contact: {}
  description: The API for comparing frogs and other things
  title: Frog Smash API
  version: "1.0"
paths:
  /compare:
    post:
      consumes:
      - application/json
      description: Records the result of a comparison between two items
      parameters:
      - description: Comparison Request
        in: body
        name: compareRequest
        required: true
        schema:
          $ref: '#/definitions/dto.CompareRequest'
      produces:
      - application/json
      responses: {}
      summary: Compare two items
  /items:
    get:
      description: Retrieves two distinct items for comparison
      produces:
      - application/json
      responses: {}
      summary: Get two items for comparison
  /leaderboard:
    get:
      description: Retrieves a paginated leaderboard of items
      produces:
      - application/json
      responses: {}
      summary: Get leaderboard
swagger: "2.0"
