definitions:
  dto.CompareRequest:
    description: Request payload for comparing two items
    properties:
      loser_id:
        type: string
      winner_id:
        type: string
    type: object
  dto.RefreshTokenRequest:
    description: Request payload for refreshing JWT token including the refresh token
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  dto.UserLoginRequest:
    description: Request payload for user login
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  dto.UserLoginResponse:
    description: Response payload for user login
    properties:
      jwt:
        type: string
      refresh_token:
        type: string
    type: object
  dto.UserRegistrationRequest:
    description: Request payload for user registration
    properties:
      email:
        type: string
      password:
        minLength: 12
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
info:
  contact: {}
  description: The API for comparing frogs and other things
  title: Frog Smash API
  version: "1.0"
paths:
  /compare:
    post:
      consumes:
      - application/json
      description: Records the result of a comparison between two items
      parameters:
      - description: Comparison Request
        in: body
        name: compareRequest
        required: true
        schema:
          $ref: '#/definitions/dto.CompareRequest'
      produces:
      - application/json
      responses: {}
      summary: Compare two items
  /items:
    get:
      description: Retrieves two distinct items for comparison
      produces:
      - application/json
      responses: {}
      summary: Get two items for comparison
  /leaderboard:
    get:
      description: Retrieves a paginated leaderboard of items
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Items per page
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses: {}
      summary: Get leaderboard
  /login:
    post:
      consumes:
      - application/json
      description: Logs in a user with username and password
      parameters:
      - description: User login payload
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.UserLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserLoginResponse'
      summary: User login
  /refresh-token:
    post:
      consumes:
      - application/json
      description: Refreshes the JWT token using a refresh token
      parameters:
      - description: Refresh token payload
        in: body
        name: token
        required: true
        schema:
          $ref: '#/definitions/dto.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserLoginResponse'
      summary: Refresh JWT token
  /register:
    post:
      consumes:
      - application/json
      description: Registers a new user with username, email, and password
      parameters:
      - description: User registration payload
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.UserRegistrationRequest'
      produces:
      - application/json
      responses: {}
      summary: Register a new user
  /upload:
    post:
      consumes:
      - multipart/form-data
      description: Uploads an image to the server
      parameters:
      - description: Image file to upload
        in: formData
        name: image
        required: true
        type: file
      produces:
      - application/json
      responses: {}
      summary: Upload an image
swagger: "2.0"
