definitions:
  dto.CompareRequest:
    description: Request payload for comparing two items
    properties:
      loser_id:
        type: string
      winner_id:
        type: string
    type: object
  dto.UserLoginRequest:
    description: Request payload for user login
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  dto.UserLoginResponse:
    description: Response payload for user login
    properties:
      jwt:
        type: string
      user:
        $ref: '#/definitions/dto.UserResponse'
    type: object
  dto.UserRegistrationRequest:
    description: Request payload for user registration
    properties:
      email:
        type: string
      password:
        minLength: 12
        type: string
    required:
    - email
    - password
    type: object
  dto.UserResponse:
    description: User data returned with login response
    properties:
      email:
        type: string
      id:
        type: string
      isVerified:
        type: boolean
    type: object
  dto.VerificationRequest:
    description: Request payload for user verification
    properties:
      code:
        type: string
    required:
    - code
    type: object
info:
  contact: {}
  description: The API for comparing frogs and other things
  title: Frog Smash API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Logs in a user with email and password
      parameters:
      - description: User login payload
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.UserLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserLoginResponse'
      summary: User login
  /auth/logout:
    post:
      consumes:
      - application/json
      description: Logs out a user by clearing the refresh token cookie
      produces:
      - application/json
      responses: {}
      summary: User logout
  /auth/me:
    get:
      description: Retrieves the currently authenticated user's information
      produces:
      - application/json
      responses: {}
      summary: Get current user
  /auth/refresh-token:
    post:
      consumes:
      - application/json
      description: Refreshes the JWT token using a refresh token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserLoginResponse'
      summary: Refresh JWT token
  /auth/register:
    post:
      consumes:
      - application/json
      description: Registers a new user with email and password
      parameters:
      - description: User registration payload
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.UserRegistrationRequest'
      produces:
      - application/json
      responses: {}
      summary: Register a new user
  /comparison/compare:
    post:
      consumes:
      - application/json
      description: Records the result of a comparison between two items
      parameters:
      - description: Comparison Request
        in: body
        name: compareRequest
        required: true
        schema:
          $ref: '#/definitions/dto.CompareRequest'
      produces:
      - application/json
      responses: {}
      summary: Compare two items
  /comparison/items:
    get:
      description: Retrieves two distinct items for comparison
      produces:
      - application/json
      responses: {}
      summary: Get two items for comparison
  /comparison/latest-submission:
    get:
      description: Retrieves the time of the latest submission by the user
      produces:
      - application/json
      responses: {}
      summary: Get time of latest submission
  /comparison/leaderboard:
    get:
      description: Retrieves a paginated leaderboard of items
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Items per page
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses: {}
      summary: Get leaderboard
  /comparison/submit-contender:
    post:
      consumes:
      - multipart/form-data
      description: Uploads an image to the server
      parameters:
      - description: Image file to upload
        in: formData
        name: image
        required: true
        type: file
      produces:
      - application/json
      responses: {}
      summary: Upload an image
  /verify:
    post:
      consumes:
      - application/json
      description: Verifies the user's email using a verification code
      parameters:
      - description: Verification code payload
        in: body
        name: code
        required: true
        schema:
          $ref: '#/definitions/dto.VerificationRequest'
      produces:
      - application/json
      responses: {}
      summary: Verify user email
  /verify/resend-email-anonymous:
    post:
      consumes:
      - application/json
      description: Resends the verification email to the user without authentication
      produces:
      - application/json
      responses: {}
      summary: Resend verification email (anonymous)
  /verify/resend-verification:
    post:
      consumes:
      - application/json
      description: Resends the verification email to the user
      produces:
      - application/json
      responses: {}
      summary: Resend verification email
swagger: "2.0"
