services:
  db: 
    # TODO: consider version and whether to use alpine
    image: postgres:18
    env_file:
      - ./api/.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      retries: 5
    
  api:
    build:
      # the directory where this is run 
      context: ./api
      # the path to the Dockerfile relative to the context
      dockerfile: ./cmd/server/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./api/.env
    depends_on:
      db:
        condition: service_healthy

  scoreupdater:
    build:
      context: ./api
      dockerfile: ./cmd/scoreupdater/Dockerfile
    env_file:
      - ./api/.env
    depends_on:
      db:
        condition: service_healthy