services:
  db: 
    # TODO: consider version and whether to use alpine
    image: postgres:18
    env_file:
      - ./api/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      retries: 5
    
  api:
    build:
      # the directory where this is run 
      context: ./api
      # the path to the Dockerfile relative to the context
      dockerfile: ./cmd/server/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./api/.env
    depends_on:
      db:
        condition: service_healthy

  scoreupdater:
    build:
      context: ./api
      dockerfile: ./cmd/scoreupdater/Dockerfile
    env_file:
      - ./api/.env
    depends_on:
      db:
        condition: service_healthy

  pgAdmin:
    image: dpage/pgadmin4:9.9
    env_file:
      - ./api/.env
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: